name: Sync to Azure DevOps

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Push to Azure DevOps
      run: |
        git config --global user.name "sarkar"
        git config --global user.email "sark@gmail.com"
        git remote add azure https://baban0315@dev.azure.com/baban0315/github-sync/_git/github-sync
        git push azure master
      env:
        AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
