on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Push to Azure DevOps
      run: |
        git config --global user.name "sark"
        git config --global user.email "sakr@gmail.com"
        git remote add azure git@ssh.dev.azure.com:v3/baban0315/github-sync/github-sync
        git push --force azure master
